---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    container_name: develop
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres?sslmode=disable
    init: true
    network_mode: service:db
    volumes:
      - ..:/workspace:cached
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
